# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: fa

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.


#tokenizer
  - name: WhitespaceTokenizer


#language model
  - name: LanguageModelFeaturizer
    model_name: bert
    model_weights: "rasa/LaBSE"

#featurizer  
  - name: LexicalSyntacticFeaturizer  
  - name: RegexFeaturizer 
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

#Entity extraction and intent recognition
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true

  - name: RegexEntityExtractor
    case_sensitive: False
    use_lookup_tables: True
    use_regexes: True

  - name: EntitySynonymMapper
   
  - name: ResponseSelector
    epochs: 200
    constrain_similarities: true

  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1


policies:
  - name: AugmentedMemoizationPolicy
    max_history: 4
  - name: TEDPolicy
    max_history: 4
    epochs: 200
    constrain_similarities: true
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True